dist: trusty
services:
  - docker
# language: ruby
# before_install:
#   - docker pull carlad/sinatra
#   - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#   - docker ps -a
#   - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
deploy:
 provider: heroku
 script:
  - docker-compose up
 api-key: $HEROKU_API_KEY
 app: service-send-mail
